main: de.raidcraft.trade.TradePlugin
name: RCTrade
version: ${project.version}#${BUILDS_ALL_TIME}
description: Provideds player and npc trades.
author: Strasse36
website: http://www.raid-craft.de
depend: [RaidCraft-API]
database: true